/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IBFactory } from "./IBFactory";

export class IBFactoryFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBFactory {
    return new Contract(address, _abi, signerOrProvider) as IBFactory;
  }
}

const _abi = [
  {
    inputs: [],
    name: "newBPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];
