/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {TransactionOverrides, TypedEventDescription, TypedFunctionDescription} from ".";

interface IBFactoryInterface extends Interface {
  functions: {
    newBPool: TypedFunctionDescription<{encode([]: []): string}>;
  };

  events: {};
}

export class IBFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IBFactory;
  attach(addressOrName: string): IBFactory;
  deployed(): Promise<IBFactory>;

  on(event: EventFilter | string, listener: Listener): IBFactory;
  once(event: EventFilter | string, listener: Listener): IBFactory;
  addListener(eventName: EventFilter | string, listener: Listener): IBFactory;
  removeAllListeners(eventName: EventFilter | string): IBFactory;
  removeListener(eventName: any, listener: Listener): IBFactory;

  interface: IBFactoryInterface;

  functions: {
    newBPool(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };

  newBPool(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    newBPool(): Promise<BigNumber>;
  };
}
