/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IBPool } from "./IBPool";

export class IBPoolFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): IBPool {
    return new Contract(address, _abi, signerOrProvider) as IBPool;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "denorm",
        type: "uint256"
      }
    ],
    name: "bind",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenBalanceOut",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "tokenWeightOut",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "poolSupply",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "totalWeight",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "tokenAmountOut",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "swapFee",
        type: "uint256"
      }
    ],
    name: "calcPoolInGivenSingleOut",
    outputs: [
      {
        internalType: "uint256",
        name: "poolAmountIn",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenBalanceIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "tokenWeightIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "poolSupply",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "totalWeight",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "tokenAmountIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "swapFee",
        type: "uint256"
      }
    ],
    name: "calcPoolOutGivenSingleIn",
    outputs: [
      {
        internalType: "uint256",
        name: "poolAmountOut",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenBalanceIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "tokenWeightIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "poolSupply",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "totalWeight",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "poolAmountOut",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "swapFee",
        type: "uint256"
      }
    ],
    name: "calcSingleInGivenPoolOut",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenAmountIn",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenBalanceOut",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "tokenWeightOut",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "poolSupply",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "totalWeight",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "poolAmountIn",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "swapFee",
        type: "uint256"
      }
    ],
    name: "calcSingleOutGivenPoolIn",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenAmountOut",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      }
    ],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [],
    name: "getCurrentTokens",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      }
    ],
    name: "getDenormalizedWeight",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [],
    name: "getTotalDenormalizedWeight",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      }
    ],
    name: "isBound",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "denorm",
        type: "uint256"
      }
    ],
    name: "rebind",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "manager",
        type: "address"
      }
    ],
    name: "setController",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "swapFee",
        type: "uint256"
      }
    ],
    name: "setSwapFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      }
    ],
    name: "unbind",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
