/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, Signer} from "ethers";
import {Provider} from "ethers/providers";

import {IKyberNetwork} from "./IKyberNetwork";

export class IKyberNetworkFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): IKyberNetwork {
    return new Contract(address, _abi, signerOrProvider) as IKyberNetwork;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "src",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "srcAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "dest",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "destAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxDestAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minConversionRate",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "walletId",
        type: "address",
      },
    ],
    name: "trade",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];
