/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IPCappedFLSmartPool } from "./IPCappedFLSmartPool";

export class IPCappedFLSmartPoolFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPCappedFLSmartPool {
    return new Contract(address, _abi, signerOrProvider) as IPCappedFLSmartPool;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address"
      },
      {
        internalType: "address",
        name: "_token",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256"
      },
      {
        internalType: "bytes",
        name: "_params",
        type: "bytes"
      }
    ],
    name: "flashLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
