/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IPCappedFLSmartPoolInterface extends Interface {
  functions: {
    flashLoan: TypedFunctionDescription<{
      encode([_receiver, _token, _amount, _params]: [
        string,
        string,
        BigNumberish,
        Arrayish
      ]): string;
    }>;
  };

  events: {};
}

export class IPCappedFLSmartPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IPCappedFLSmartPool;
  attach(addressOrName: string): IPCappedFLSmartPool;
  deployed(): Promise<IPCappedFLSmartPool>;

  on(event: EventFilter | string, listener: Listener): IPCappedFLSmartPool;
  once(event: EventFilter | string, listener: Listener): IPCappedFLSmartPool;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IPCappedFLSmartPool;
  removeAllListeners(eventName: EventFilter | string): IPCappedFLSmartPool;
  removeListener(eventName: any, listener: Listener): IPCappedFLSmartPool;

  interface: IPCappedFLSmartPoolInterface;

  functions: {
    flashLoan(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _params: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  flashLoan(
    _receiver: string,
    _token: string,
    _amount: BigNumberish,
    _params: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    flashLoan(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _params: Arrayish
    ): Promise<BigNumber>;
  };
}
