/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IPSmartPool } from "./IPSmartPool";

export class IPSmartPoolFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPSmartPool {
    return new Contract(address, _abi, signerOrProvider) as IPSmartPool;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256"
      }
    ],
    name: "exitPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256"
      }
    ],
    name: "joinPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
