/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IPSmartPoolInterface extends Interface {
  functions: {
    exitPool: TypedFunctionDescription<{
      encode([_amount]: [BigNumberish]): string;
    }>;

    joinPool: TypedFunctionDescription<{
      encode([_amount]: [BigNumberish]): string;
    }>;
  };

  events: {};
}

export class IPSmartPool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IPSmartPool;
  attach(addressOrName: string): IPSmartPool;
  deployed(): Promise<IPSmartPool>;

  on(event: EventFilter | string, listener: Listener): IPSmartPool;
  once(event: EventFilter | string, listener: Listener): IPSmartPool;
  addListener(eventName: EventFilter | string, listener: Listener): IPSmartPool;
  removeAllListeners(eventName: EventFilter | string): IPSmartPool;
  removeListener(eventName: any, listener: Listener): IPSmartPool;

  interface: IPSmartPoolInterface;

  functions: {
    exitPool(
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    joinPool(
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  exitPool(
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  joinPool(
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    exitPool(_amount: BigNumberish): Promise<BigNumber>;

    joinPool(_amount: BigNumberish): Promise<BigNumber>;
  };
}
