/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IUniswapExchange } from "./IUniswapExchange";

export class IUniswapExchangeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapExchange {
    return new Contract(address, _abi, signerOrProvider) as IUniswapExchange;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "min_liquidity",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      }
    ],
    name: "addLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "payable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address"
      },
      {
        internalType: "address",
        name: "_spender",
        type: "address"
      }
    ],
    name: "allowance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_spender",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256"
      }
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address"
      }
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "min_tokens",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      }
    ],
    name: "ethToTokenSwapInput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "payable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      }
    ],
    name: "ethToTokenSwapOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "eth_sold",
        type: "uint256"
      }
    ],
    stateMutability: "payable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "min_tokens",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      }
    ],
    name: "ethToTokenTransferInput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "payable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      }
    ],
    name: "ethToTokenTransferOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "eth_sold",
        type: "uint256"
      }
    ],
    stateMutability: "payable",
    type: "function"
  },
  {
    inputs: [],
    name: "factoryAddress",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eth_sold",
        type: "uint256"
      }
    ],
    name: "getEthToTokenInputPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    name: "getEthToTokenOutputPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "eth_sold",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    name: "getTokenToEthInputPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "eth_bought",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eth_bought",
        type: "uint256"
      }
    ],
    name: "getTokenToEthOutputPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_tokens",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      }
    ],
    name: "removeLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token_addr",
        type: "address"
      }
    ],
    name: "setup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "tokenAddress",
    outputs: [
      {
        internalType: "address",
        name: "token",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      }
    ],
    name: "tokenToEthSwapInput",
    outputs: [
      {
        internalType: "uint256",
        name: "eth_bought",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eth_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      }
    ],
    name: "tokenToEthSwapOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      }
    ],
    name: "tokenToEthTransferInput",
    outputs: [
      {
        internalType: "uint256",
        name: "eth_bought",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eth_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      }
    ],
    name: "tokenToEthTransferOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "exchange_addr",
        type: "address"
      }
    ],
    name: "tokenToExchangeSwapInput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_eth_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "exchange_addr",
        type: "address"
      }
    ],
    name: "tokenToExchangeSwapOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      },
      {
        internalType: "address",
        name: "exchange_addr",
        type: "address"
      }
    ],
    name: "tokenToExchangeTransferInput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_eth_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      },
      {
        internalType: "address",
        name: "exchange_addr",
        type: "address"
      }
    ],
    name: "tokenToExchangeTransferOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "token_addr",
        type: "address"
      }
    ],
    name: "tokenToTokenSwapInput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_eth_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "token_addr",
        type: "address"
      }
    ],
    name: "tokenToTokenSwapOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "min_eth_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      },
      {
        internalType: "address",
        name: "token_addr",
        type: "address"
      }
    ],
    name: "tokenToTokenTransferInput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_bought",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_tokens_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "max_eth_sold",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address"
      },
      {
        internalType: "address",
        name: "token_addr",
        type: "address"
      }
    ],
    name: "tokenToTokenTransferOutput",
    outputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256"
      }
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address"
      },
      {
        internalType: "address",
        name: "_to",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256"
      }
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];
