/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IUniswapExchangeInterface extends Interface {
  functions: {
    addLiquidity: TypedFunctionDescription<{
      encode([min_liquidity, max_tokens, deadline]: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    allowance: TypedFunctionDescription<{
      encode([_owner, _spender]: [string, string]): string;
    }>;

    approve: TypedFunctionDescription<{
      encode([_spender, _value]: [string, BigNumberish]): string;
    }>;

    balanceOf: TypedFunctionDescription<{ encode([_owner]: [string]): string }>;

    ethToTokenSwapInput: TypedFunctionDescription<{
      encode([min_tokens, deadline]: [BigNumberish, BigNumberish]): string;
    }>;

    ethToTokenSwapOutput: TypedFunctionDescription<{
      encode([tokens_bought, deadline]: [BigNumberish, BigNumberish]): string;
    }>;

    ethToTokenTransferInput: TypedFunctionDescription<{
      encode([min_tokens, deadline, recipient]: [
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    ethToTokenTransferOutput: TypedFunctionDescription<{
      encode([tokens_bought, deadline, recipient]: [
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    factoryAddress: TypedFunctionDescription<{ encode([]: []): string }>;

    getEthToTokenInputPrice: TypedFunctionDescription<{
      encode([eth_sold]: [BigNumberish]): string;
    }>;

    getEthToTokenOutputPrice: TypedFunctionDescription<{
      encode([tokens_bought]: [BigNumberish]): string;
    }>;

    getTokenToEthInputPrice: TypedFunctionDescription<{
      encode([tokens_sold]: [BigNumberish]): string;
    }>;

    getTokenToEthOutputPrice: TypedFunctionDescription<{
      encode([eth_bought]: [BigNumberish]): string;
    }>;

    removeLiquidity: TypedFunctionDescription<{
      encode([amount, min_eth, min_tokens, deadline]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    setup: TypedFunctionDescription<{ encode([token_addr]: [string]): string }>;

    tokenAddress: TypedFunctionDescription<{ encode([]: []): string }>;

    tokenToEthSwapInput: TypedFunctionDescription<{
      encode([tokens_sold, min_eth, deadline]: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    tokenToEthSwapOutput: TypedFunctionDescription<{
      encode([eth_bought, max_tokens, deadline]: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    tokenToEthTransferInput: TypedFunctionDescription<{
      encode([tokens_sold, min_eth, deadline, recipient]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    tokenToEthTransferOutput: TypedFunctionDescription<{
      encode([eth_bought, max_tokens, deadline, recipient]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    tokenToExchangeSwapInput: TypedFunctionDescription<{
      encode([
        tokens_sold,
        min_tokens_bought,
        min_eth_bought,
        deadline,
        exchange_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    tokenToExchangeSwapOutput: TypedFunctionDescription<{
      encode([
        tokens_bought,
        max_tokens_sold,
        max_eth_sold,
        deadline,
        exchange_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    tokenToExchangeTransferInput: TypedFunctionDescription<{
      encode([
        tokens_sold,
        min_tokens_bought,
        min_eth_bought,
        deadline,
        recipient,
        exchange_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string,
        string
      ]): string;
    }>;

    tokenToExchangeTransferOutput: TypedFunctionDescription<{
      encode([
        tokens_bought,
        max_tokens_sold,
        max_eth_sold,
        deadline,
        recipient,
        exchange_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string,
        string
      ]): string;
    }>;

    tokenToTokenSwapInput: TypedFunctionDescription<{
      encode([
        tokens_sold,
        min_tokens_bought,
        min_eth_bought,
        deadline,
        token_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    tokenToTokenSwapOutput: TypedFunctionDescription<{
      encode([
        tokens_bought,
        max_tokens_sold,
        max_eth_sold,
        deadline,
        token_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string
      ]): string;
    }>;

    tokenToTokenTransferInput: TypedFunctionDescription<{
      encode([
        tokens_sold,
        min_tokens_bought,
        min_eth_bought,
        deadline,
        recipient,
        token_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string,
        string
      ]): string;
    }>;

    tokenToTokenTransferOutput: TypedFunctionDescription<{
      encode([
        tokens_bought,
        max_tokens_sold,
        max_eth_sold,
        deadline,
        recipient,
        token_addr
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        string,
        string
      ]): string;
    }>;

    totalSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    transfer: TypedFunctionDescription<{
      encode([_to, _value]: [string, BigNumberish]): string;
    }>;

    transferFrom: TypedFunctionDescription<{
      encode([_from, _to, value]: [string, string, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class IUniswapExchange extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IUniswapExchange;
  attach(addressOrName: string): IUniswapExchange;
  deployed(): Promise<IUniswapExchange>;

  on(event: EventFilter | string, listener: Listener): IUniswapExchange;
  once(event: EventFilter | string, listener: Listener): IUniswapExchange;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IUniswapExchange;
  removeAllListeners(eventName: EventFilter | string): IUniswapExchange;
  removeListener(eventName: any, listener: Listener): IUniswapExchange;

  interface: IUniswapExchangeInterface;

  functions: {
    addLiquidity(
      min_liquidity: BigNumberish,
      max_tokens: BigNumberish,
      deadline: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    allowance(_owner: string, _spender: string): Promise<BigNumber>;

    approve(
      _spender: string,
      _value: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    balanceOf(_owner: string): Promise<BigNumber>;

    ethToTokenSwapInput(
      min_tokens: BigNumberish,
      deadline: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    ethToTokenSwapOutput(
      tokens_bought: BigNumberish,
      deadline: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    ethToTokenTransferInput(
      min_tokens: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    ethToTokenTransferOutput(
      tokens_bought: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    factoryAddress(): Promise<string>;

    getEthToTokenInputPrice(eth_sold: BigNumberish): Promise<BigNumber>;

    getEthToTokenOutputPrice(tokens_bought: BigNumberish): Promise<BigNumber>;

    getTokenToEthInputPrice(tokens_sold: BigNumberish): Promise<BigNumber>;

    getTokenToEthOutputPrice(eth_bought: BigNumberish): Promise<BigNumber>;

    removeLiquidity(
      amount: BigNumberish,
      min_eth: BigNumberish,
      min_tokens: BigNumberish,
      deadline: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setup(
      token_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenAddress(): Promise<string>;

    tokenToEthSwapInput(
      tokens_sold: BigNumberish,
      min_eth: BigNumberish,
      deadline: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToEthSwapOutput(
      eth_bought: BigNumberish,
      max_tokens: BigNumberish,
      deadline: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToEthTransferInput(
      tokens_sold: BigNumberish,
      min_eth: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToEthTransferOutput(
      eth_bought: BigNumberish,
      max_tokens: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToExchangeSwapInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      exchange_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToExchangeSwapOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      exchange_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToExchangeTransferInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      exchange_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToExchangeTransferOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      exchange_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToTokenSwapInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      token_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToTokenSwapOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      token_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToTokenTransferInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      token_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tokenToTokenTransferOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      token_addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    totalSupply(): Promise<BigNumber>;

    transfer(
      _to: string,
      _value: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      _from: string,
      _to: string,
      value: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  addLiquidity(
    min_liquidity: BigNumberish,
    max_tokens: BigNumberish,
    deadline: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  allowance(_owner: string, _spender: string): Promise<BigNumber>;

  approve(
    _spender: string,
    _value: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  balanceOf(_owner: string): Promise<BigNumber>;

  ethToTokenSwapInput(
    min_tokens: BigNumberish,
    deadline: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  ethToTokenSwapOutput(
    tokens_bought: BigNumberish,
    deadline: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  ethToTokenTransferInput(
    min_tokens: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  ethToTokenTransferOutput(
    tokens_bought: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  factoryAddress(): Promise<string>;

  getEthToTokenInputPrice(eth_sold: BigNumberish): Promise<BigNumber>;

  getEthToTokenOutputPrice(tokens_bought: BigNumberish): Promise<BigNumber>;

  getTokenToEthInputPrice(tokens_sold: BigNumberish): Promise<BigNumber>;

  getTokenToEthOutputPrice(eth_bought: BigNumberish): Promise<BigNumber>;

  removeLiquidity(
    amount: BigNumberish,
    min_eth: BigNumberish,
    min_tokens: BigNumberish,
    deadline: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setup(
    token_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenAddress(): Promise<string>;

  tokenToEthSwapInput(
    tokens_sold: BigNumberish,
    min_eth: BigNumberish,
    deadline: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToEthSwapOutput(
    eth_bought: BigNumberish,
    max_tokens: BigNumberish,
    deadline: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToEthTransferInput(
    tokens_sold: BigNumberish,
    min_eth: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToEthTransferOutput(
    eth_bought: BigNumberish,
    max_tokens: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToExchangeSwapInput(
    tokens_sold: BigNumberish,
    min_tokens_bought: BigNumberish,
    min_eth_bought: BigNumberish,
    deadline: BigNumberish,
    exchange_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToExchangeSwapOutput(
    tokens_bought: BigNumberish,
    max_tokens_sold: BigNumberish,
    max_eth_sold: BigNumberish,
    deadline: BigNumberish,
    exchange_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToExchangeTransferInput(
    tokens_sold: BigNumberish,
    min_tokens_bought: BigNumberish,
    min_eth_bought: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    exchange_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToExchangeTransferOutput(
    tokens_bought: BigNumberish,
    max_tokens_sold: BigNumberish,
    max_eth_sold: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    exchange_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToTokenSwapInput(
    tokens_sold: BigNumberish,
    min_tokens_bought: BigNumberish,
    min_eth_bought: BigNumberish,
    deadline: BigNumberish,
    token_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToTokenSwapOutput(
    tokens_bought: BigNumberish,
    max_tokens_sold: BigNumberish,
    max_eth_sold: BigNumberish,
    deadline: BigNumberish,
    token_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToTokenTransferInput(
    tokens_sold: BigNumberish,
    min_tokens_bought: BigNumberish,
    min_eth_bought: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    token_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tokenToTokenTransferOutput(
    tokens_bought: BigNumberish,
    max_tokens_sold: BigNumberish,
    max_eth_sold: BigNumberish,
    deadline: BigNumberish,
    recipient: string,
    token_addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  totalSupply(): Promise<BigNumber>;

  transfer(
    _to: string,
    _value: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferFrom(
    _from: string,
    _to: string,
    value: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    addLiquidity(
      min_liquidity: BigNumberish,
      max_tokens: BigNumberish,
      deadline: BigNumberish
    ): Promise<BigNumber>;

    allowance(_owner: string, _spender: string): Promise<BigNumber>;

    approve(_spender: string, _value: BigNumberish): Promise<BigNumber>;

    balanceOf(_owner: string): Promise<BigNumber>;

    ethToTokenSwapInput(
      min_tokens: BigNumberish,
      deadline: BigNumberish
    ): Promise<BigNumber>;

    ethToTokenSwapOutput(
      tokens_bought: BigNumberish,
      deadline: BigNumberish
    ): Promise<BigNumber>;

    ethToTokenTransferInput(
      min_tokens: BigNumberish,
      deadline: BigNumberish,
      recipient: string
    ): Promise<BigNumber>;

    ethToTokenTransferOutput(
      tokens_bought: BigNumberish,
      deadline: BigNumberish,
      recipient: string
    ): Promise<BigNumber>;

    factoryAddress(): Promise<BigNumber>;

    getEthToTokenInputPrice(eth_sold: BigNumberish): Promise<BigNumber>;

    getEthToTokenOutputPrice(tokens_bought: BigNumberish): Promise<BigNumber>;

    getTokenToEthInputPrice(tokens_sold: BigNumberish): Promise<BigNumber>;

    getTokenToEthOutputPrice(eth_bought: BigNumberish): Promise<BigNumber>;

    removeLiquidity(
      amount: BigNumberish,
      min_eth: BigNumberish,
      min_tokens: BigNumberish,
      deadline: BigNumberish
    ): Promise<BigNumber>;

    setup(token_addr: string): Promise<BigNumber>;

    tokenAddress(): Promise<BigNumber>;

    tokenToEthSwapInput(
      tokens_sold: BigNumberish,
      min_eth: BigNumberish,
      deadline: BigNumberish
    ): Promise<BigNumber>;

    tokenToEthSwapOutput(
      eth_bought: BigNumberish,
      max_tokens: BigNumberish,
      deadline: BigNumberish
    ): Promise<BigNumber>;

    tokenToEthTransferInput(
      tokens_sold: BigNumberish,
      min_eth: BigNumberish,
      deadline: BigNumberish,
      recipient: string
    ): Promise<BigNumber>;

    tokenToEthTransferOutput(
      eth_bought: BigNumberish,
      max_tokens: BigNumberish,
      deadline: BigNumberish,
      recipient: string
    ): Promise<BigNumber>;

    tokenToExchangeSwapInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      exchange_addr: string
    ): Promise<BigNumber>;

    tokenToExchangeSwapOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      exchange_addr: string
    ): Promise<BigNumber>;

    tokenToExchangeTransferInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      exchange_addr: string
    ): Promise<BigNumber>;

    tokenToExchangeTransferOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      exchange_addr: string
    ): Promise<BigNumber>;

    tokenToTokenSwapInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      token_addr: string
    ): Promise<BigNumber>;

    tokenToTokenSwapOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      token_addr: string
    ): Promise<BigNumber>;

    tokenToTokenTransferInput(
      tokens_sold: BigNumberish,
      min_tokens_bought: BigNumberish,
      min_eth_bought: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      token_addr: string
    ): Promise<BigNumber>;

    tokenToTokenTransferOutput(
      tokens_bought: BigNumberish,
      max_tokens_sold: BigNumberish,
      max_eth_sold: BigNumberish,
      deadline: BigNumberish,
      recipient: string,
      token_addr: string
    ): Promise<BigNumber>;

    totalSupply(): Promise<BigNumber>;

    transfer(_to: string, _value: BigNumberish): Promise<BigNumber>;

    transferFrom(
      _from: string,
      _to: string,
      value: BigNumberish
    ): Promise<BigNumber>;
  };
}
