/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { ReentryProtection } from "./ReentryProtection";

export class ReentryProtectionFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<ReentryProtection> {
    return super.deploy() as Promise<ReentryProtection>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): ReentryProtection {
    return super.attach(address) as ReentryProtection;
  }
  connect(signer: Signer): ReentryProtectionFactory {
    return super.connect(signer) as ReentryProtectionFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentryProtection {
    return new Contract(address, _abi, signerOrProvider) as ReentryProtection;
  }
}

const _abi = [
  {
    inputs: [],
    name: "rpSlot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060bc8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063830df85214602d575b600080fd5b60336049565b6040518082815260200191505060405180910390f35b6040518080606560229139602201905060405180910390208156fe5265656e74727950726f74656374696f6e2e73746f726167652e6c6f636174696f6ea26469706673582212205ad4a11cbcf21732b3a34032760192d0bab9c8586dd259be4c4b1ddadb73dd8964736f6c63430006040033";
